#!/usr/bin/env bash
set -euo pipefail

if [ "${1:-}" = "ptlaaxobimwroe" ]; then
	#cli called back into borger to print help. avoid extra 🍔
	shift
else
	echo 🍔
fi

FOUND_PROJECT=false
dir="$(pwd -P)"

while true; do
	#walk up the directory tree, determine where the root of the repo
	#is by querying git config whether there is a submodule called
	#borger at the repo root
	if git config --file "$dir/.gitmodules" \
		--get-regexp '^submodule\..*\.path$' '^borger$' >/dev/null 2>&1; then
		FOUND_PROJECT=true
		cd "$dir"
		
		#submodule needs to have been initialized; otherwise cli.sh won't exist
		if [ -z "$(git submodule status borger 2>/dev/null)" ] || \
			[ "$(git submodule status borger 2>/dev/null | cut -c1)" = "-" ]; then
			git submodule update --init --recursive
		fi
		
		break
	fi
	
	[ "$dir" = "/" ] && break
	dir="$(dirname "$dir")"
done

cmd_init()
{
	if [ -z "${1:-}" ]; then
		echo "ERROR: directory name is required"
		echo "Usage: borger init <dir>"
		exit 1
	fi
	
	set -x
	local DIR="$1"
	
	git clone --recurse-submodules https://github.com/BorgerLand/BlankTemplate.git "$DIR"
	cd "$DIR"
	borger/cli.sh ptlaaxobimwroe postinit
}

cmd_help()
{
	echo "Usage: borger <command>"
	echo ""
	echo "Commands:"
	echo "  init <dir>     Scaffold a new project in the given directory name, then automatically run install"
	
	if $FOUND_PROJECT; then
		borger/cli.sh ptlaaxobimwroe help
	fi
	echo "  help, --help, -h"
}

case "${1:-}" in
	init)
		shift
		cmd_init "$@"
		;;
	help|--help|-h)
		cmd_help
		;;
	*)
		if $FOUND_PROJECT; then
			#forward the unknown command to the project's specific cli
			exec borger/cli.sh ptlaaxobimwroe "$@"
		fi
		
		cmd_help
		exit 1
		;;
esac
